[package]
name = "2020-day1"
version = "0.1.0"
authors = ["hashworks <mail@hashworks.net>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
itertools = "0.9.0"